export const initialData = [
    {
      id: '1',
      title: 'FAHRWERK',
      color: '#20878b',
      vehicles: 37,
      nok: 28,
      nokVin: 0.757,
      target: 0.8,
      topIssues: [
        { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
        { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
        { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
        { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
        { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
      ],
    },
    {
      id: '2',
      title: 'ZP6',
      color: '#f24f4f',
      vehicles: 37,
      nok: 21,
      nokVin: 0.568,
      target: 0.8,
      topIssues: [
        { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
        { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
        { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
        { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
        { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
      ],
    },
    {
      id: '3',
      title: 'BANCOS',
      color: '#ffd666',
      vehicles: 28,
      nok: 47,
      nokVin: 1.679,
      target: 0.8,
      topIssues: [
        { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
        { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
        { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
        { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
        { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
      ],
    },
    {
      id: '4',
      title: 'BANCOS',
      color: '#f24f4f',
      // color: '#f52f2f',
      vehicles: 28,
      nok: 47,
      nokVin: 1.679,
      target: 0.8,
      topIssues: [
        { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
        { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
        { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
        { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
        { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
      ],
    },
    {
      id: '5',
      title: 'ZP6',
      color: '#20878b',
      vehicles: 37,
      nok: 21,
      nokVin: 0.568,
      target: 0.8,
      topIssues: [
        { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
        { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
        { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
        { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
        { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
      ],
    },
    {
      id: '6',
      title: 'ZP6',
      color: '#20878b', // #2c7562 #38816f #448d7a #296c5b #228488 #12595e #20878b #10555c,
      vehicles: 37,
      nok: 21,
      nokVin: 0.568,
      target: 0.8,
      topIssues: [
        { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
        { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
        { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
        { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
        { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
      ],
    },
  ]