export const initialData = [
  {
    id: '1',
    title: 'MAKITA',
    // color: '#20878b',
    color: 'success',
    vehicles: 37,
    nok: 28,
    nokVin: 0.757,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
      { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
      { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
      { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
      { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
    ],
  },
  {
    id: '2',
    title: 'ZP6',
    // color: '#f24f4f',
    color: 'warning',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '3',
    title: 'BANCOS',
    // color: '#f24f4f',
    color: 'error',
    vehicles: 28,
    nok: 47,
    nokVin: 0.679,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Banco Novo Polo", occurrences: 8 },
      { code: '3109 01', description: 'Banco Polo Track ', occurrences: 4 },
      { code: '3182 01', description: 'Banco UP', occurrences: 3 },
      { code: '6902 01', description: 'Banco Gol  ', occurrences: 3 },
      { code: '4107 01', description: 'Banco Polo TSI', occurrences: 3 },
    ],
  },
  {
    id: '4',
    title: 'TACTO12',
    color: 'error',
    // color: '#f52f2f',
    vehicles: 28,
    nok: 47,
    nokVin: 0.679,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
      { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
      { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
      { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
      { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
    ],
  },
  {
    id: '5',
    title: 'R2',
    // color: '#20878b',
    color: 'error',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '6',
    title: 'FRONTEND',
    // color: '#20878b', 
    // #2c7562 #38816f #448d7a #296c5b #228488 #12595e #20878b #10555c,
    color: 'error',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '7',
    title: 'FAHRWERK2',
    // color: '#20878b',
    color: 'success',
    vehicles: 37,
    nok: 28,
    nokVin: 0.757,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
      { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
      { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
      { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
      { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
    ],
  },
  {
    id: '8',
    title: 'ZP62',
    // color: '#f24f4f',
    color: 'warning',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '9',
    title: 'BANCOS2',
    // color: '#f24f4f',
    color: 'error',
    vehicles: 28,
    nok: 47,
    nokVin: 0.679,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Banco Novo Polo", occurrences: 8 },
      { code: '3109 01', description: 'Banco Polo Track ', occurrences: 4 },
      { code: '3182 01', description: 'Banco UP', occurrences: 3 },
      { code: '6902 01', description: 'Banco Gol  ', occurrences: 3 },
      { code: '4107 01', description: 'Banco Polo TSI', occurrences: 3 },
    ],
  },
  {
    id: '10',
    title: 'TACTO11',
    color: 'error',
    // color: '#f52f2f',
    vehicles: 28,
    nok: 47,
    nokVin: 0.679,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
      { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
      { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
      { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
      { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
    ],
  },
  {
    id: '11',
    title: 'R3',
    // color: '#20878b',
    color: 'error',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '12',
    title: 'FRONTEND2',
    // color: '#20878b', 
    // #2c7562 #38816f #448d7a #296c5b #228488 #12595e #20878b #10555c,
    color: 'error',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '13',
    title: 'FAHRWERK2',
    // color: '#20878b',
    color: 'success',
    vehicles: 37,
    nok: 28,
    nokVin: 0.757,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
      { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
      { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
      { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
      { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
    ],
  },
  {
    id: '14',
    title: 'ZP63',
    // color: '#f24f4f',
    color: 'warning',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '15',
    title: 'BANCOS3',
    // color: '#f24f4f',
    color: 'error',
    vehicles: 28,
    nok: 47,
    nokVin: 0.679,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Banco Novo Polo", occurrences: 8 },
      { code: '3109 01', description: 'Banco Polo Track ', occurrences: 4 },
      { code: '3182 01', description: 'Banco UP', occurrences: 3 },
      { code: '6902 01', description: 'Banco Gol  ', occurrences: 3 },
      { code: '4107 01', description: 'Banco Polo TSI', occurrences: 3 },
    ],
  },
  {
    id: '16',
    title: 'TACTO10',
    color: 'error',
    // color: '#f52f2f',
    vehicles: 28,
    nok: 47,
    nokVin: 0.679,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2490 01', description: "Bomba d'água", occurrences: 8 },
      { code: '3109 01', description: 'Suporte quadro auxiliar LE', occurrences: 4 },
      { code: '3182 01', description: 'Quadro Auxiliar LD', occurrences: 3 },
      { code: '6902 01', description: 'Travessas na carroceria', occurrences: 3 },
      { code: '4107 01', description: 'Suporte bomba de vácuo', occurrences: 3 },
    ],
  },
  {
    id: '17',
    title: 'R1',
    // color: '#20878b',
    color: 'error',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
  {
    id: '18',
    title: 'FRONTEND3',
    // color: '#20878b', 
    // #2c7562 #38816f #448d7a #296c5b #228488 #12595e #20878b #10555c,
    color: 'error',
    vehicles: 37,
    nok: 21,
    nokVin: 0.568,
    targetAlert: 0.6,
    targetCritical: 0.8,
    topIssues: [
      { code: '2638 01', description: 'Duto freio no agregado hidráulico', occurrences: 4 },
      { code: '3402 01', description: 'Roda dianteira LD', occurrences: 3 },
      { code: '4237 01', description: 'Dobradiças porta traseira LE', occurrences: 2 },
      { code: '2640 01', description: 'Duto freio agregado hidráulico 740', occurrences: 2 },
      { code: '4208 01', description: 'Batente da tampa dianteira LD', occurrences: 2 },
    ],
  },
]